#!/bin/sh

$HOME/.config/bspwm/autostart.sh

bspc config border_width         2
bspc config window_gap           4
bspc config top_padding          30
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config ignore_ewmh_focus true
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"

bspc monitor -d 1 2 3 4 5

bspc rule -a Spotify desktop='^5'
bspc rule -a Vlc state=fullscreen
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen
bspc rule -a Arandr state=floating
bspc rule -a Arcolinux-tweak-tool.py state=floating
bspc rule -a Arcolinux-welcome-app.py state=floating
bspc rule -a Arcolinux-calamares-tool.py state=floating
bspc rule -a feh state=floating
bspc rule -a Galculator state=floating
bspc rule -a Oblogout state=floating
bspc rule -a Xfce4-terminal state=floating
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Google-chrome desktop='^1' follow=on
bspc rule -a Code desktop='^4' follow=on
bspc rule -a Alacritty desktop='^3' follow=on
bspc rule -a jetbrains-studio state=floating border=off follow=on
bspc rule -a Lutris state=floating border=off
bspc rule -a discord desktop='^5'
bspc rule -a 'TeamSpeak 3' desktop='^5'